dependencies:
  - name: payment-api
    version: ~2.0.6
    repository: '@hmctspublic'
    condition: ccpay.payment-api.enabled

  - name: postgresql
    version: ~6.3.5
    repository: '@stable'
    condition: ccpay.postgresql.enabled

  - name: ccpay-bubble-frontend
    version: ~0.1.2
    repository: '@hmctspublic'
    condition: ccpay.ccpay-bubble-frontend.enabled

  - name: fees-register-api
    version: ~0.0.8
    repository: '@hmctspublic'
    condition: ccpay.fees-register-api.enabled

  - name: rpe-service-auth-provider
    version: ~0.2.5
    repository: '@hmctspublic'
    condition: ccpay.rpe-service-auth-provider.enabled

  - name: ccpay-bulkscanning-api
    version: ~0.0.8
    repository: '@hmctspublic'
    condition: ccpay.ccpay-bulkscanning-api.enabled

  - name: ccd
    version: 4.0.2
    repository: '@hmctspublic'
    condition: ccpay.ccd.enabled

