payment-api:
  java:
    secrets:
      PCI_PAL_ACCOUNT_ID_CMC:
        disabled: true
      PCI_PAL_ACCOUNT_ID_PROBATE:
        disabled: true
      PCI_PAL_ACCOUNT_ID_DIVORCE:
        disabled: true
      PCI_PAL_API_URL:
        disabled: true
      PCI_PAL_API_KEY:
        disabled: true
      GOV_PAY_ACCOUNT_PROBATE:
        disabled: true
      GOV_PAY_ACCOUNT_DIVORCE:
        disabled: true
    environment:
      GOV_PAY_AUTH_KEY_CMC: la0ohpqa9er1bub2hddieeesc6sabbbqn4smkkve7s9ailn3n9d3hbnhc3
      GOV_PAY_AUTH_KEY_DIVORCE_FRONTEND: la0ohpqa9er1bub2hddieeesc6sabbbqn4smkkve7s9ailn3n9d3hbnhc3
      GOV_PAY_AUTH_KEY_PROBATE_FRONTEND: la0ohpqa9er1bub2hddieeesc6sabbbqn4smkkve7s9ailn3n9d3hbnhc3
      #TODO use CCD Chart instead
      CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
global:
  idamApiUrl: idam-api.aat.platform.hmcts.net